### ISSUE TITLE
Hide dash X not working on 3.38.1

### ISSUE THREAD

**Issue by rxvisser** [Edenhofer/Minimalism-Gnome-Shell#11]
Hide dash X does not seems to do anything on 3.38.1 on arch. No error is shown on the tweak tool.
The only log-entry on the system relating to the extension is the following:

> 5668542-Nov 02 19:29:46 laptop gnome-shell[1775]: Usage of object.actor is deprecated for ViewSelector
5668543-                                              get@resource:///org/gnome/shell/ui/environment.js:314:29
5668544:                                              _init@/home/rxvisser/.local/share/gnome-shell/extensions/**hide-dash**@xenatt.github.com/extension.js:46:4
5668545-                                              wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
5668546-                                              _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
5668547-                                              newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
5668548:                                              init@/home/rxvisser/.local/share/gnome-shell/extensions/**hide-dash**@xenatt.github.com/extension.js:19:9
5668549-                                              _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:428:50
5668550-                                              _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:145:18
5668551-                                              _onEnabledExtensionsChanged/<@ resource:///org/gnome/shell/ui/extensionSystem.js:491:35
5668552-                                              _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:491:14

Not sure if it is relevant.

**Comment by rxvisser** [comment]
It is solely a problem with the shell version check. I propose a fix in #12

**Comment by Edenhofer** [comment]
Thanks again for you pull request to fix the issue!
