### ISSUE TITLE
Replace native 'super' key

### ISSUE THREAD

**Issue by romainPrignon** [Edenhofer/Minimalism-Gnome-Shell#2]
Hi,
I'm wondering how can I use the 'super' key in order to display the menu 'all the application'

I'm using debian

Thank you :-)

**Comment by Edenhofer** [comment]
It should be super+A. In case you want to remap those shortcuts just dig through the keyboard --> shortcuts settings in the GNOME settings.
I am glad to help but filing a bug for this purpose is not appropiate.
